# Generated by Django 3.2.9 on 2021-11-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorits', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
